name = "Insignias BRAF"
author = "BRAF Team"
prefix = "braf_insignias"
mainprefix = "braf"
[version]
major = 1
minor = 0
patch = 0
build = 0

[hemtt.launch.default]
workshop = [
  "450814997", # CBA
  "463939057", # ACE
  "623475643", # 3den enhanced
  "1779063631" # Zeus enhanced
]